# Generated by Django 5.0.1 on 2026-03-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('cargo_type', models.CharField(choices=[('general', 'General Cargo'), ('perishable', 'Perishable Goods'), ('hazardous', 'Hazardous Materials'), ('oversized', 'Oversized Freight'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_currency', models.CharField(default='USD', max_length=3)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='quotes_quot_created_51e95a_idx'), models.Index(fields=['status'], name='quotes_quot_status_cead77_idx')],
            },
        ),
    ]
