# Generated by Django 5.1.5 on 2026-03-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_email',
            field=models.CharField(default='hello@tradehub.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(default='info@globalexports.com', max_length=200),
        ),
    ]
