# Generated by Django 6.0.3 on 2026-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_email_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_commitment',
            field=models.TextField(default="We're committed to transparency, reliability, and building long-term partnerships that drive mutual success."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_founded_sub',
            field=models.CharField(default='Delivering excellence in global trade since 2004', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_founded_text',
            field=models.CharField(default='Trusted by Fortune 500 Companies', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.TextField(default='Your trusted partner in global logistics. Connecting businesses worldwide with seamless import-export solutions.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_primary',
            field=models.CharField(default='Request a Quote', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_secondary',
            field=models.CharField(default='Our Products', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_badge',
            field=models.CharField(default='PRODUCT CATALOG', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_subtitle',
            field=models.TextField(default='Discover our curated selection of high-quality products from trusted global suppliers'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_title',
            field=models.CharField(default='Premium Import Solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_badge',
            field=models.CharField(default='Get Started', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_subtitle',
            field=models.TextField(default='Get a personalized shipping quote tailored to your specific needs. Our logistics experts will analyze your requirements and provide competitive pricing within 24 hours.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quote_title',
            field=models.CharField(default='Request a Custom Quote', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_subtitle',
            field=models.TextField(default='Comprehensive import-export solutions designed to streamline your global trade operations'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_title',
            field=models.CharField(default='Our Services', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_countries_label',
            field=models.CharField(default='Countries Served', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_shipments_label',
            field=models.CharField(default='Shipments Delivered', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_success_label',
            field=models.CharField(default='Success Rate', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_success_rate',
            field=models.CharField(default='99.8%', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_years_label',
            field=models.CharField(default='Years Experience', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_sat',
            field=models.CharField(default='10 AM - 4 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_address',
            field=models.CharField(default='Addis Ababa, Ethiopia', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(default='Addis Ababa, Ethiopia', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+251 991 001 124', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.CharField(blank=True, default='https://facebook.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.CharField(blank=True, default='https://instagram.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.CharField(blank=True, default='https://linkedin.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.CharField(blank=True, default='https://twitter.com', max_length=300),
        ),
    ]
