# Generated by Django 4.2.17 on 2026-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0003_sitesettings_about_commitment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_badge',
            field=models.CharField(default='Our Story', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_subtitle',
            field=models.TextField(default='At TradeFlow, we specialize in connecting businesses across the globe. With years of experience in import and export, we pride ourselves on delivering reliable, efficient, and transparent services.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_title',
            field=models.CharField(default='About Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_badge',
            field=models.CharField(default='Insights & Updates', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_subtitle',
            field=models.TextField(default='Stay updated with the latest insights, trends, and tips in global trade and logistics. Our blog covers everything from import/export regulations to industry news.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_page_title',
            field=models.CharField(default='Our Blog', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_badge',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_subtitle',
            field=models.TextField(default="We're here to help with your import and export needs. Reach out to our team and we'll get back to you within 24 hours."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title',
            field=models.CharField(default='Get in Touch', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_page_badge',
            field=models.CharField(default='Our Offerings', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_page_subtitle',
            field=models.TextField(default='We provide comprehensive import and export solutions tailored to your business needs. From seamless international shipping to customs clearance, we ensure your goods reach their destination safely.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_page_title',
            field=models.CharField(default='Services & Products', max_length=200),
        ),
    ]
