# Generated by Django 4.2.17 on 2026-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0005_sitesettings_about_cta_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blog_cta_subtitle',
            field=models.TextField(default='Let our experts help you navigate global commerce with confidence'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_cta_title',
            field=models.TextField(default='Ready to Optimize Your Trade Operations?'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_hero_badge',
            field=models.TextField(default='Insights & Resources'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_hero_subtitle',
            field=models.TextField(default='Expert perspectives on global trade, logistics innovation, and market trends'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='blog_hero_title',
            field=models.TextField(default='Trade Intelligence & Industry Insights'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cert1_name',
            field=models.TextField(default='ISO 9001:2015'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cert2_name',
            field=models.TextField(default='AEO Certified'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cert3_name',
            field=models.TextField(default='IATA Member'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cert4_name',
            field=models.TextField(default='C-TPAT Verified'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cert5_name',
            field=models.TextField(default='5-Star Rating'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cert6_name',
            field=models.TextField(default='FMC Licensed'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_sat',
            field=models.TextField(default='10 AM - 4 PM'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_sun',
            field=models.TextField(default='Closed'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_weekday',
            field=models.TextField(default='9 AM - 6 PM'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_stat1_desc',
            field=models.TextField(default='Served worldwide'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_stat1_title',
            field=models.TextField(default='50+ Countries'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_stat2_desc',
            field=models.TextField(default='Always here to help'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_stat2_title',
            field=models.TextField(default='24/7 Support'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_stat3_desc',
            field=models.TextField(default='10+ years experience'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_stat3_title',
            field=models.TextField(default='Expert Team'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_services_badge',
            field=models.TextField(default='CORE SERVICES'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_services_subtitle',
            field=models.TextField(default='From initial planning to final delivery, our comprehensive suite of services ensures your international trade operations run seamlessly.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_services_title',
            field=models.TextField(default='Everything You Need for Global Trade Success'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs1_desc',
            field=models.TextField(default='End-to-end supply chain management with real-time tracking across air, sea, and land transportation networks.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs1_f1',
            field=models.TextField(default='Multi-modal shipping'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs1_f2',
            field=models.TextField(default='Real-time tracking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs1_f3',
            field=models.TextField(default='Global network'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs1_title',
            field=models.TextField(default='Global Logistics'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs2_desc',
            field=models.TextField(default='Expert documentation and regulatory compliance services to ensure smooth passage through international borders.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs2_f1',
            field=models.TextField(default='Expert documentation'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs2_f2',
            field=models.TextField(default='Regulatory compliance'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs2_f3',
            field=models.TextField(default='Fast processing'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs2_title',
            field=models.TextField(default='Customs Clearance'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs3_desc',
            field=models.TextField(default='Strategic optimization and analytics to maximize efficiency, reduce costs, and improve delivery performance.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs3_f1',
            field=models.TextField(default='Cost optimization'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs3_f2',
            field=models.TextField(default='Performance analytics'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs3_f3',
            field=models.TextField(default='Strategic planning'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fs3_title',
            field=models.TextField(default='Supply Chain Management'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_badge',
            field=models.TextField(default='Your Global Trade Partner'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_cta_btn',
            field=models.TextField(default='Get Started Today'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_cta_subtitle',
            field=models.TextField(default='Join hundreds of companies who trust us to handle their international trade operations.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_cta_title',
            field=models.TextField(default='Ready to Expand Your Global Reach?'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_feat1_desc',
            field=models.TextField(default='Navigate regulations across 150+ countries with confidence'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_feat1_title',
            field=models.TextField(default='Compliance Excellence'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_feat2_desc',
            field=models.TextField(default='Scale operations without operational bottlenecks'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_feat2_title',
            field=models.TextField(default='Growth Focused'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_feat3_desc',
            field=models.TextField(default='Expert guidance from dedicated trade specialists'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_feat3_title',
            field=models.TextField(default='24/7 Support'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_highlight1',
            field=models.TextField(default='ISO 9001 & 14001 Certified Operations'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_highlight2',
            field=models.TextField(default='AEO & C-TPAT Trusted Partner Status'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_highlight3',
            field=models.TextField(default='Real-time Shipment Tracking & Visibility'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_highlight4',
            field=models.TextField(default='Customs Clearance in 150+ Countries'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_inner_title',
            field=models.TextField(default='Turning Trade Complexity Into Your Competitive Edge'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_section_title',
            field=models.TextField(default='For Modern Business'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_quote',
            field=models.TextField(default='"Every shipment represents a business dream, a market opportunity, and economic growth. We\'re proud to be the bridge that makes global commerce possible."'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_quote_author',
            field=models.TextField(default='— TradeFlow Leadership Team'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_badge',
            field=models.TextField(default='CLIENT SUCCESS STORIES'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_subtitle',
            field=models.TextField(default='See what our enterprise clients say about their experience'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_title',
            field=models.TextField(default='Trusted by Global Leaders'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_bar_badge',
            field=models.TextField(default='TRUSTED BY INDUSTRY LEADERS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_bar_statement',
            field=models.TextField(default='Our certifications ensure your cargo moves safely, legally, and efficiently through every checkpoint, customs office, and border crossing worldwide.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_bar_title',
            field=models.TextField(default='Certified & Compliant Across All Major Trade Corridors'),
        ),
    ]
